### ISSUE TITLE
Cannot Extend/Deploy JX2 Large Deployable Antenna

### ISSUE THREAD

**Issue by whytf** [KSPSnark/JX2Antenna#1]
Hello,
I can't deploy or extend JX2 Large Deployable Antenna while on surface or in orbit.
I have latest KSP steam version.
If it helps KSP.log is attached.
[KSP.log](https://github.com/KSPSnark/JX2Antenna/files/2307303/KSP.log)

**Comment by KSPSnark** [comment]
Just tried it myself.  I used KSP 1.4.5 (the latest released version), running JX2Antenna 2.0.2 (also the latest released version).

Extends and retracts just fine, no problem.

Therefore, there's some issue with your particular installation.  Examples of possible problems may include, 

- running an outdated version of KSP (you didn't mention a version number)
- running an outdated version of JX2Antenna (you didn't mention a version number)
- some problem with how you've installed JX2Antenna
- some interaction with some other mod somewhere on your system

From glancing at your log file, it looks as though you're running a _ton_ of mods, so I wouldn't be surprised if the problem lies there.  Have you tried running a clean KSP with _only_ JX2Antenna installed?  If it works fine when you do that, then that indicates the problem is with one of your other mods, so it's just a process of elimination for you to work out which one.

In any case, the mod _itself_ seems to be fine, so I'll close this issue.  If you'd like to discuss further, or dig into the matter (e.g. see whether anyone else has run into your problem, etc.), probably the best place to ask is in the [mod's forum thread](https://forum.kerbalspaceprogram.com/index.php?/topic/153125-145-jx2antenna-v205-giant-1000g-antenna-for-big-solar-systems/).

**Comment by whytf** [comment]
As i said i am using Latest KSP on steam 1.4.5.2243
I installed JX2 with ckan (latest 2.0.5)

**Comment by KILLERMANTV** [comment]
I SOLVED IT!!
I Installed Remote Tech and it Works!!
